import type { Data, Skill, SkillId } from "./types";

export const SKILLS: Skill[] = [
  { id: "ux", name: "UX design", cluster: "Craft" },
  { id: "brand", name: "Brand", cluster: "Craft" },
  { id: "writing", name: "Writing", cluster: "Craft" },
  { id: "research", name: "Research", cluster: "Craft" },
  { id: "frontend", name: "Frontend", cluster: "Build" },
  { id: "fullstack", name: "Full-stack development", cluster: "Build" },
  { id: "ai", name: "AI engineering", cluster: "Build" },
  { id: "data", name: "Data", cluster: "Build" },
  { id: "product", name: "Product", cluster: "Build" },
  { id: "urban", name: "Urban strategy", cluster: "Place" },
  { id: "stakeholder", name: "Stakeholder work", cluster: "Place" },
  { id: "facilitation", name: "Facilitation", cluster: "Place" },
];

export function skillName(id: SkillId | string) {
  return SKILLS.find((skill) => skill.id === id)?.name ?? id;
}

export const SEED: Data = {
  people: [
    {
      id: "luke",
      name: "Luke Zetzema",
      role: "Founder · Connector · Builder",
      location: "Amsterdam, Netherlands",
      about:
        "I build the conditions for people and organizations to act together. Action = Matter is the network I wanted when a question was bigger than my own team.",
      skills: ["product", "facilitation", "urban", "writing"],
      interests: ["Civic prototypes", "Plain language", "Small teams"],
      goals: [
        "Prove a need can become a team in a day",
        "Keep City Lab honest to the neighborhood",
      ],
      availability: "now",
      orgId: "am",
      services: ["Frame a collaboration", "Hold a first working session"],
      experience: [
        { title: "Founder", org: "Action = Matter", span: "2024 — now" },
        { title: "Program lead", org: "City experiments", span: "2019 — 2024" },
      ],
    },
    {
      id: "anna",
      name: "Anna Visser",
      role: "UX designer",
      location: "Amsterdam",
      about:
        "I design the moments where a service either earns trust or loses it. Most of my work is with teams who are allergic to theatre.",
      skills: ["ux", "brand", "research"],
      interests: ["Service journeys", "Public interfaces"],
      goals: ["Ship work people understand in the first minute"],
      availability: "month",
      orgId: "studio",
      services: ["Journey and service design", "Research sprints"],
      experience: [{ title: "Design lead", org: "Studio Noord", span: "2021 — now" }],
    },
    {
      id: "mateo",
      name: "Mateo Ruiz",
      role: "Full-stack engineer",
      location: "Utrecht",
      about:
        "I build the thing the meeting agreed to. I care more about the first working week than the architecture diagram.",
      skills: ["frontend", "fullstack"],
      interests: ["Clear interfaces", "Boring infrastructure"],
      goals: ["Stay close to a product someone actually uses"],
      availability: "month",
      orgId: "haven",
      services: ["Product engineering", "Site builds"],
      experience: [{ title: "Engineer", org: "Haven Labs", span: "2022 — now" }],
    },
    {
      id: "noor",
      name: "Noor El-Amin",
      role: "AI engineer",
      location: "Amersfoort",
      about:
        "I work on systems that have to explain themselves. If a match cannot say why, it should not be shown.",
      skills: ["ai", "fullstack", "data"],
      interests: ["Explainable systems", "Local models of work"],
      goals: ["Keep intelligence in service of a next action"],
      availability: "now",
      orgId: "veld",
      services: ["Applied AI", "Matching and retrieval"],
      experience: [{ title: "Engineer", org: "Veld AI", span: "2023 — now" }],
    },
    {
      id: "sara",
      name: "Sarah de Jong",
      role: "Urban Planner · Architect · Connector",
      location: "Amsterdam, Netherlands",
      about:
        "I design and develop urban spaces that bring people together. I am passionate about sustainable cities and creative collaboration.",
      skills: ["urban", "stakeholder", "facilitation", "ux"],
      interests: ["Interesting projects", "Creative partners", "Impact investors", "City initiatives"],
      goals: ["Open one honest pilot this spring"],
      availability: "now",
      orgId: "gemeente",
      services: ["Urban Design", "Project Development", "Sustainability", "Workshops", "City Labs"],
      experience: [{ title: "Strategist", org: "Gemeente Amersfoort", span: "2018 — now" }],
    },
    {
      id: "jonas",
      name: "Jonas Berg",
      role: "Product partner",
      location: "Rotterdam",
      about:
        "I help founders decide what not to build. I am booked ahead, and I only take work with a named outcome.",
      skills: ["product", "writing"],
      interests: ["Scope", "Decision logs"],
      goals: ["Fewer projects, clearer ones"],
      availability: "later",
      orgId: "berg",
      services: ["Product critique", "Scope for a first release"],
      experience: [{ title: "Independent partner", org: "Berg & Co", span: "2020 — now" }],
    },
    {
      id: "elise",
      name: "Elise Martens",
      role: "Brand director",
      location: "Haarlem",
      about:
        "I make an identity people can repeat without a deck. I would rather be specific than polished.",
      skills: ["brand", "writing"],
      interests: ["Verbal identity", "Print that gets used"],
      goals: ["One system a small team can actually carry"],
      availability: "now",
      orgId: "studio",
      services: ["Identity systems", "Naming and voice"],
      experience: [{ title: "Brand director", org: "Studio Noord", span: "2017 — now" }],
    },
    {
      id: "kim",
      name: "Kim Alderliesten",
      role: "Community lead",
      location: "Amersfoort",
      about:
        "I know who actually shows up. A project that cannot name its neighbors is not ready to meet in public.",
      skills: ["facilitation", "stakeholder"],
      interests: ["Hosting", "Neighborhood memory"],
      goals: ["Keep City Lab in the room with residents"],
      availability: "now",
      orgId: "am",
      services: ["Community hosting", "Public sessions"],
      experience: [{ title: "Community lead", org: "Action = Matter", span: "2024 — now" }],
    },
    {
      id: "vitali",
      name: "Vitali Petrov",
      role: "Workflow Systems",
      location: "Amsterdam, Netherlands",
      about: "I turn repetitive sales work into a workflow a team can actually trust.",
      skills: ["ai", "data", "product"],
      interests: ["Automation", "Sales systems"],
      goals: ["Ship one workflow a team keeps using"],
      availability: "now",
      orgId: "techforward",
      services: ["Workflow Systems", "AI Automation"],
      experience: [{ title: "Systems lead", org: "TechForward", span: "2023 — now" }],
    },
    {
      id: "mark",
      name: "Mark Peterson",
      role: "AI Automation Specialist",
      location: "Berlin",
      about: "I connect sales teams with the automation that removes the manual follow-up.",
      skills: ["ai", "product", "fullstack"],
      interests: ["Sales process", "Practical AI"],
      goals: ["Make follow-up faster without losing the human"],
      availability: "month",
      orgId: "techforward",
      services: ["AI automation", "Sales workflows"],
      experience: [{ title: "Automation specialist", org: "TechForward", span: "2022 — now" }],
    },
  ],
  orgs: [
    {
      id: "am",
      name: "Action = Matter",
      kind: "Studio",
      location: "Amersfoort",
      about:
        "A network for turning a real need into a team and a team into work. We stay small so the introduction stays honest.",
      capabilities: ["Collaboration design", "Civic prototypes", "Product direction"],
      services: ["First working session", "Network match", "Project framing"],
      needs: ["UX design on City Lab", "An engineer who will explain the matcher"],
      team: ["luke", "kim"],
      partners: ["studio", "veld", "gemeente", "haven", "berg"],
      capacity: "Two people free for a focused sprint this month.",
      resources: ["A room in Amersfoort", "The City Lab brief", "This network"],
      exposed: true,
    },
    {
      id: "studio",
      name: "Studio Noord",
      kind: "Design practice",
      location: "Amsterdam",
      about: "A design practice for services and identities that have to survive contact with the public.",
      capabilities: ["UX design", "Brand systems", "Research"],
      services: ["Journey design", "Identity"],
      needs: ["Build partners who will not over-scope"],
      team: ["anna", "elise"],
      partners: ["am"],
      capacity: "Anna this month. Elise available now.",
      resources: ["Research archive", "A print studio in Haarlem"],
      exposed: true,
    },
    {
      id: "veld",
      name: "Veld AI",
      kind: "Engineering studio",
      location: "Amersfoort",
      about: "Applied intelligence for teams who need a reason, not a score.",
      capabilities: ["AI engineering", "Data", "Product engineering"],
      services: ["Matching systems", "Internal assistants"],
      needs: ["Problems with a human decision at the end"],
      team: ["noor"],
      partners: ["am"],
      capacity: "Noor can start this month.",
      resources: ["Evaluation notes from two earlier matchers"],
      exposed: true,
    },
    {
      id: "gemeente",
      name: "Gemeente Amersfoort",
      kind: "Municipality",
      location: "Amersfoort",
      about: "The city side of City Lab. Partnership is possible when the team can hold both residents and the brief.",
      capabilities: ["Urban strategy", "Permits and land", "Public process"],
      services: ["Pilot partnership"],
      needs: ["A team for a spring pilot on the eastern edge"],
      team: ["sara"],
      partners: ["am"],
      capacity: "Sara is booked ahead. A pilot slot is open if the ask is specific.",
      resources: ["Map layers, still with the survey team", "A Thursday walk"],
      exposed: true,
    },
    {
      id: "haven",
      name: "Haven Labs",
      kind: "Product studio",
      location: "Utrecht",
      about: "A small product studio. The public site no longer explains the work, and the work is good.",
      capabilities: ["Product engineering", "Frontend"],
      services: ["Builds", "Technical partnership"],
      needs: ["Design and brand for a new site"],
      team: ["mateo"],
      partners: ["am"],
      capacity: "Mateo can join a design pairing this month.",
      resources: ["Current site", "A list of what must not be generic"],
      exposed: true,
    },
    {
      id: "berg",
      name: "Berg & Co",
      kind: "Practice",
      location: "Rotterdam",
      about: "Product partnership for teams who need a decision more than a roadmap.",
      capabilities: ["Product", "Writing"],
      services: ["Scope", "Critique"],
      needs: ["Fewer, sharper engagements"],
      team: ["jonas"],
      partners: ["am"],
      capacity: "Booked ahead.",
      resources: ["A short decision log template"],
      exposed: true,
    },
    {
      id: "techforward",
      name: "TechForward",
      kind: "Company",
      location: "Netherlands",
      about: "We are looking for an AI-enabled workflow to make our sales process faster and more efficient.",
      capabilities: ["AI", "Innovation", "Education"],
      services: ["Sales systems", "Workflow design"],
      needs: ["An AI workflow for sales"],
      team: ["vitali", "mark"],
      partners: ["am"],
      capacity: "Open for a three to six month collaboration.",
      resources: ["Current sales process map"],
      exposed: true,
    },
  ],
  projects: [
    {
      id: "citylab",
      name: "Hof City Lab",
      status: "active",
      ownerId: "luke",
      orgId: "am",
      objective: "Connecting people and initiatives for a vibrant, innovative and inclusive city.",
      summary: "Connecting people and initiatives for a vibrant, innovative and inclusive city.",
      location: "Amersfoort, Netherlands",
      skillIds: ["urban", "stakeholder", "ux", "facilitation"],
      memberIds: ["luke", "sara", "kim"],
      tags: ["City Development", "Innovation", "Culture"],
      stats: { people: 24, organizations: 11, opportunities: 7 },
      needs: [
        { title: "Architect", detail: "Urban design and spatial planning", personId: "anna" },
        { title: "Hospitality partner", detail: "For events and community", personId: "elise" },
        { title: "Urban strategist", detail: "City development expertise", personId: "jonas" },
      ],
      timeline: [
        { id: "tl1", label: "Edge named", when: "Last month", done: true },
        { id: "tl2", label: "Walk with the municipality", when: "Thursday", done: false },
        { id: "tl3", label: "Public table", when: "Next", done: false },
      ],
      documents: [
        {
          id: "d1",
          title: "District brief",
          kind: "Brief",
          body: "The eastern edge is planned on paper and unused on foot. The lab exists to test one change while it is still cheap to reverse. The municipality will open a pilot if the team can name who it is for.",
        },
        {
          id: "d2",
          title: "Walk notes",
          kind: "Note",
          body: "Sara can walk it Thursday. Kim will invite neighbors who came last spring. The missing piece is someone who can turn what we hear into a service people recognize.",
        },
      ],
      outcome: "",
      updatedAt: 4,
    },
    {
      id: "platform",
      name: "A=M Platform",
      status: "active",
      ownerId: "luke",
      orgId: "am",
      objective: "A single place where a need becomes a team, and a team becomes the next action.",
      summary: "The product itself. Matching must stay explainable. The golden path is the whole product.",
      location: "Amersfoort",
      skillIds: ["product", "fullstack", "ai", "ux"],
      memberIds: ["luke", "noor"],
      timeline: [
        { id: "tl4", label: "Golden paths named", when: "Done", done: true },
        { id: "tl5", label: "Reasons in the open", when: "This week", done: false },
        { id: "tl6", label: "Question becomes a project", when: "Now", done: false },
      ],
      documents: [
        {
          id: "d3",
          title: "Golden paths",
          kind: "Note",
          body: "Registration is a living profile. A question becomes requirements, skills, a project, and people. A connection becomes a conversation and a team. Work becomes tasks. The assistant proposes; a person confirms.",
        },
      ],
      outcome: "",
      updatedAt: 3,
    },
    {
      id: "table",
      name: "Public table series",
      status: "forming",
      ownerId: "sara",
      orgId: "gemeente",
      objective: "A rhythm of evenings where the district can argue with the plan while it is still cheap to change.",
      summary: "Hosted evenings on the edge. Needs a writer and a host who are not afraid of a public room.",
      location: "Amersfoort",
      skillIds: ["facilitation", "writing", "stakeholder"],
      memberIds: ["sara"],
      timeline: [
        { id: "tl7", label: "First evening", when: "Thursday", done: false },
        { id: "tl8", label: "Notes back to the brief", when: "The week after", done: false },
      ],
      documents: [
        {
          id: "d4",
          title: "Evening shape",
          kind: "Note",
          body: "Ninety minutes. One map. No slides. Someone writes down what the room refused.",
        },
      ],
      outcome: "",
      updatedAt: 2,
    },
    {
      id: "haven-site",
      name: "Haven Labs site",
      status: "forming",
      ownerId: "mateo",
      orgId: "haven",
      objective: "Replace a site that hides the work with one that asks the right people to begin.",
      summary: "Haven Labs needs design and brand beside the engineer who will build the pages.",
      location: "Utrecht",
      skillIds: ["ux", "brand", "frontend"],
      memberIds: ["mateo"],
      timeline: [
        { id: "tl9", label: "Hear the need", when: "This week", done: false },
        { id: "tl10", label: "First page", when: "This month", done: false },
      ],
      documents: [
        {
          id: "d5",
          title: "What must not be generic",
          kind: "Note",
          body: "Mateo wrote: no stock city skylines, no gradient orbs, no claim we cannot show in a project.",
        },
      ],
      outcome: "",
      updatedAt: 1,
    },
  ],
  tasks: [
    {
      id: "t1",
      projectId: "citylab",
      title: "Walk the eastern edge with Sara",
      status: "today",
      ownerId: "luke",
      note: "Thursday. Bring the brief, not a deck.",
    },
    {
      id: "t2",
      projectId: "citylab",
      title: "Send Anna the journey constraint",
      status: "today",
      ownerId: "luke",
      note: "City Lab still has no designer in the room.",
    },
    {
      id: "t3",
      projectId: "platform",
      title: "Write match reasons in plain language",
      status: "week",
      ownerId: "luke",
    },
    {
      id: "t4",
      projectId: "citylab",
      title: "Receive municipal map layers",
      status: "waiting",
      ownerId: "sara",
      note: "With the survey team.",
    },
    {
      id: "t5",
      projectId: "platform",
      title: "Choose hosting",
      status: "blocked",
      ownerId: "luke",
      note: "Waiting on a vendor answer.",
    },
    {
      id: "t6",
      projectId: "platform",
      title: "Draw the first capability map",
      status: "done",
      ownerId: "luke",
    },
  ],
  connections: [
    {
      id: "c-kim",
      personId: "kim",
      projectId: "citylab",
      status: "connected",
      why: "You build Action = Matter together.",
    },
    {
      id: "c-sara",
      personId: "sara",
      projectId: "citylab",
      status: "connected",
      why: "Municipal partner on City Lab.",
    },
    {
      id: "c-noor",
      personId: "noor",
      projectId: "platform",
      status: "connected",
      why: "Building the platform together.",
    },
  ],
  messages: [
    {
      id: "m1",
      threadId: "project:citylab",
      authorId: "sara",
      body: "The map layers are with the survey team. I can walk the edge on Thursday.",
      atLabel: "Yesterday",
    },
    {
      id: "m2",
      threadId: "project:citylab",
      authorId: "luke",
      body: "We had a great session today with new partners. Let's keep the momentum going!",
      atLabel: "This morning",
    },
    {
      id: "m3",
      threadId: "project:citylab",
      authorId: "kim",
      body: "I'll invite the neighbors who came last spring.",
      atLabel: "This morning",
    },
    {
      id: "m4",
      threadId: "project:platform",
      authorId: "noor",
      body: "The matcher should explain itself. If we can't say why, we shouldn't show the person.",
      atLabel: "Yesterday",
    },
    {
      id: "m5",
      threadId: "project:platform",
      authorId: "luke",
      body: "Agreed. Reasons stay in the open.",
      atLabel: "Yesterday",
    },
    {
      id: "m6",
      threadId: "dm:sara",
      authorId: "sara",
      body: "I'll be on foot, not in a meeting room.",
      atLabel: "Tue",
    },
  ],
  opportunities: [
    {
      id: "sales-ai",
      title: "AI workflow for sales",
      kind: "Project",
      orgId: "techforward",
      skillIds: ["ai", "product", "fullstack"],
      budget: "€ 25.000 – 50.000",
      location: "Netherlands (hybrid)",
      timeline: "3–6 months",
      summary: "We are looking for an AI-enabled workflow to make our sales process faster and more efficient.",
      leadId: "vitali",
      tags: ["AI", "Automation", "Sales", "Workflow"],
      seeking: [
        { personId: "noor", label: "AI Specialist" },
        { personId: "vitali", label: "Workflow Developer" },
        { personId: "mark", label: "Sales Process Expertise" },
      ],
    },
    {
      id: "green-urban",
      title: "Green Urban Future",
      kind: "Project",
      orgId: "gemeente",
      projectId: "citylab",
      skillIds: ["urban", "facilitation"],
      budget: "Shared pilot",
      location: "Amersfoort",
      timeline: "This season",
      summary: "Sustainable city solutions for a neighborhood that wants to try one change while it is still reversible.",
      leadId: "sara",
      tags: ["Sustainability", "City"],
    },
    {
      id: "ai-dev",
      title: "AI developer needed",
      kind: "Role",
      orgId: "am",
      projectId: "platform",
      skillIds: ["ai", "fullstack"],
      budget: "Retained collaboration",
      location: "Amersfoort",
      timeline: "Six weeks",
      summary: "The platform needs someone who can build the matcher and keep its reasons honest.",
      leadId: "noor",
    },
    {
      id: "district",
      title: "District partnership",
      kind: "Partnership",
      orgId: "gemeente",
      projectId: "citylab",
      skillIds: ["urban", "facilitation"],
      budget: "Shared pilot cost",
      location: "Amersfoort",
      timeline: "This spring",
      summary: "The municipality will open a pilot if a team can hold both the residents and the brief.",
      leadId: "sara",
    },
    {
      id: "brand-sys",
      title: "Identity for City Lab",
      kind: "Service",
      orgId: "studio",
      projectId: "citylab",
      skillIds: ["brand", "ux"],
      budget: "Fixed engagement",
      location: "Amsterdam",
      timeline: "Three weeks",
      summary: "A visual and verbal system the lab can use without hiring a brand department.",
      leadId: "elise",
    },
    {
      id: "open-table",
      title: "Open table evening",
      kind: "Event",
      orgId: "am",
      projectId: "table",
      skillIds: ["facilitation"],
      budget: "Hosted",
      location: "Amersfoort",
      timeline: "Thursday",
      summary: "An evening in the district. The work needs people who can listen in public.",
      leadId: "kim",
    },
    {
      id: "haven-web",
      title: "Website for Haven Labs",
      kind: "Project",
      orgId: "haven",
      projectId: "haven-site",
      skillIds: ["ux", "brand", "frontend"],
      budget: "To be scoped",
      location: "Utrecht",
      timeline: "This month",
      summary: "A site that explains the work and asks the right person to begin.",
      leadId: "mateo",
    },
  ],
  notices: [
    {
      id: "n1",
      text: "Anna Visser is a strong match for City Lab.",
      href: "/projects/citylab",
      when: "Today",
      read: false,
    },
    {
      id: "n2",
      text: "Map layers are still with the municipality.",
      href: "/action",
      when: "Today",
      read: false,
    },
    {
      id: "n3",
      text: "A district partnership is open for the spring.",
      href: "/opportunities",
      when: "Yesterday",
      read: false,
    },
  ],
  workflows: [
    {
      id: "w1",
      projectId: "citylab",
      steps: [
        { id: "s1", title: "Name the edge", detail: "The place is chosen.", state: "done" },
        {
          id: "s2",
          title: "Walk it with the municipality",
          detail: "Thursday, on foot, with the brief.",
          state: "now",
        },
        {
          id: "s3",
          title: "Invite a designer into the room",
          detail: "Someone who can hold what the walk reveals.",
          state: "next",
        },
        {
          id: "s4",
          title: "Hold a public table",
          detail: "Neighbors argue with the plan while it is still cheap.",
          state: "next",
        },
      ],
    },
    {
      id: "w2",
      projectId: "platform",
      steps: [
        { id: "s5", title: "Name the golden paths", detail: "The product is the path, not the modules.", state: "done" },
        {
          id: "s6",
          title: "Explain every match",
          detail: "Reasons in language a person can refuse.",
          state: "now",
        },
        {
          id: "s7",
          title: "Turn a question into a project",
          detail: "Need, skills, people, confirmation.",
          state: "next",
        },
      ],
    },
    {
      id: "w3",
      projectId: "table",
      steps: [
        { id: "s8", title: "Set the room", detail: "One map. No slides.", state: "now" },
        { id: "s9", title: "Invite the writers and hosts", detail: "The series is not staffed.", state: "next" },
      ],
    },
    {
      id: "w4",
      projectId: "haven-site",
      steps: [
        { id: "s10", title: "Hear the need", detail: "What the site must make someone do.", state: "now" },
        { id: "s11", title: "Pair design and build", detail: "Brand, UX, and Mateo.", state: "next" },
      ],
    },
  ],
};

export function fresh(): Data {
  return structuredClone(SEED);
}
