/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActionRouteImport } from './routes/_app/action'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppOrgsIdRouteImport } from './routes/_app/orgs.$id'
import { Route as AppPeopleIdRouteImport } from './routes/_app/people.$id'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActionRoute = AppActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIdRoute = AppOrgsIdRouteImport.update({
  id: '/orgs/$id',
  path: '/orgs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/action': typeof AppActionRoute
  '/ai': typeof AppAiRoute
  '/me': typeof AppMeRoute
  '/network': typeof AppNetworkRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/orgs/$id': typeof AppOrgsIdRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/action': typeof AppActionRoute
  '/ai': typeof AppAiRoute
  '/me': typeof AppMeRoute
  '/network': typeof AppNetworkRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/': typeof AppIndexRoute
  '/orgs/$id': typeof AppOrgsIdRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/action': typeof AppActionRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/me': typeof AppMeRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orgs/$id': typeof AppOrgsIdRoute
  '/_app/people/$id': typeof AppPeopleIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action'
    | '/ai'
    | '/me'
    | '/network'
    | '/opportunities'
    | '/orgs/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/action'
    | '/ai'
    | '/me'
    | '/network'
    | '/opportunities'
    | '/'
    | '/orgs/$id'
    | '/people/$id'
    | '/projects/$id'
    | '/projects'
  id:
    | '__root__'
    | '/_app'
    | '/_app/action'
    | '/_app/ai'
    | '/_app/me'
    | '/_app/network'
    | '/_app/opportunities'
    | '/_app/'
    | '/_app/orgs/$id'
    | '/_app/people/$id'
    | '/_app/projects/$id'
    | '/_app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action': {
      id: '/_app/action'
      path: '/action'
      fullPath: '/action'
      preLoaderRoute: typeof AppActionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$id': {
      id: '/_app/orgs/$id'
      path: '/orgs/$id'
      fullPath: '/orgs/$id'
      preLoaderRoute: typeof AppOrgsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionRoute: typeof AppActionRoute
  AppAiRoute: typeof AppAiRoute
  AppMeRoute: typeof AppMeRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrgsIdRoute: typeof AppOrgsIdRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionRoute: AppActionRoute,
  AppAiRoute: AppAiRoute,
  AppMeRoute: AppMeRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrgsIdRoute: AppOrgsIdRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
